name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # إعداد Flutter باستخدام إصدار محدد
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'  # حدد الإصدار الذي تريده هنا

      # تثبيت الاعتماديات
      - name: Install dependencies
        run: flutter pub get

      # تحليل المشروع
      - name: Analyze project source
        run: flutter analyze

      # تشغيل الاختبارات
      - name: Run tests
        run: flutter test
